feat(templates): add javascript compiler
nxtedition/nxt-lib pull request #38
Opened 2022-10-07 16:16 UTC by kmamal

First iteration. I have done some basic testing and I think it works. Best way to try it is to run `yarn pack` in `nxt-lib` and then in the `asset` service `yarn install [path to pack file]`.

* Instead of using the `[[ ... ]]` syntax, I've decided to stick with `{{ ... }}`, and to extend it with a "language selector"
    * `{{ ... }}` uses old familiar nxtpressions
    * `{{#nxt ... }}` does the same
    * `{{#js ... }}` uses the new javascript syntax

* I've not used RecordAtom or mobx. There's some basic reactive logic inside an Observable. The only confusing part might be the `unusedRecordIds`? But let me know if you want me to do something else.
* I'm setting some of the node.js globals to `undefined` to avoid errors and including `_`, 'fp', and `moment` by default.

As an example the old nxtpression...

`{{ id | asset(\"general\") | ds(\":general.title\", \"value\") }}`

...will now look like...

`{{#js ds(ctx.id + ':asset.types')?.value?.includes('general') ? ds(ctx.id + ':general.title')?.value : undefined }}`

2022-10-07 16:34 UTC, ronag commented on util/template/javascript.js
> +              .pipe(rx.distinctUntilChanged(fp.isEqual))
```suggestion
```

2022-10-07 16:34 UTC, ronag reviewed
this needs tests

2022-10-07 16:36 UTC, ronag commented on util/template/javascript.js
> +          const callScript = _.debounce(() => {
i'd prefer just a next tick if "dirty"

2022-10-07 16:56 UTC, ronag commented
I made a try for simplification:

```js
export default function ({ script, context, ds }) {
  return new rxjs.Observable(o => {
    const records = new Map()
    let dirty = false
    
    function callScript () {
      dirty = false
    
      try {
        o.next(script(context, getRecord)) // TODO (fix): https://nodejs.org/api/vm.html
      } catch (err) {
        o.error(err)
      }

      for (const [recordId, entry] of records) {
        entry.refs -= 1
        if (entry.refs === 0) {
          entry.record.unref()
          entry.record.off('update', refresh)
          records.delete(recordId)
        }
      }
    }
    
    function refresh () {
      if (!dirty) {
        dirty = true
        process.nextTick(callScript)
      }
    }
    
    function getRecord (recordId) {
      let entry = records.get(recordId)
      if (!entry) {
        entry = { refs: 0, record: ds.record.getRecord(recordId) }
        entry.record.on('update', refresh) // TODO (fix): Check for value change
        records.set(recordId, entry)
      }
      entry.refs += 1
      return entry.record.data
    }
    
    callScript()

    return () => {
      for (const entry of records) {
        entry.record.unref()
        entry.record.off('update', refresh)
      }
    }
  })
}
```

2022-10-10 16:44 UTC, kmamal commented
Pushed fixes. Ref counting doesn't really work in this case because a record could be referenced twice in the same expression. Replaced it with a boolean `isActive`.

2022-10-11 12:15 UTC, ronag commented on util/template/javascript.js
> +              // TODO (fix): Convert to state
Fix

2022-10-11 12:16 UTC, ronag commented on util/template/javascript.js
> +        'ctx',
$

2022-10-11 12:16 UTC, ronag commented on util/template/javascript.js
> +        'ds',
nxt, nxt.ds

2022-10-11 12:16 UTC, ronag commented on util/template/javascript.js
> +const globals = { _, fp, moment }
date-fns, luxor?

2022-10-11 12:18 UTC, ronag commented on util/template/javascript.js
> +
const args = [                
  ...new Array(overrides.length),
   ...Object.values(globals),
   context,
   getRecord
]

2022-10-11 12:19 UTC, ronag commented on util/template/javascript.js
> +  'WebAssembly',
...Object.keys(globalThis)

2022-10-11 12:21 UTC, ronag commented on util/template/javascript.js
> +  'WebAssembly',
https://nodejs.org/api/globals.html

2022-10-11 12:30 UTC, ronag commented on util/template/javascript.js
> +
```suggestion
if (state == null) {
  state = recordId.startsWith('{') || recordId.includes('?') ? ds.record.PROVIDER  ds.record.SERVER
}
```

2022-10-11 12:30 UTC, deadbeef84 commented on util/template/javascript.js
> +        ...overrides,
Perhaps spread overrides at end, then you wont even have to pass them when calling the function.

2022-10-11 12:31 UTC, deadbeef84 commented on util/template/javascript.js
> +        ...overrides,
or including overrides in globals, and let them be set to undefined there

2022-10-11 12:47 UTC, deadbeef84 commented on util/template/javascript.js
> +              // TODO (fix): https://nodejs.org/api/vm.html
Using the vm module would be nice, then you wouldn't need `ctx.x` but could access context variables directly... I guess you could do the same here, but then you would need to recreate the function whenever context keys change.

2022-10-11 12:47 UTC, deadbeef84 commented on util/template/javascript.js
> +              // TODO (fix): https://nodejs.org/api/vm.html
I guess vm module also complicates the getRecord method...?

2022-10-11 12:48 UTC, ronag commented on util/template/javascript.js
> +              // TODO (fix): https://nodejs.org/api/vm.html
I think the problem with vm is passing stuff in and out... I'm not sure it will work

2022-10-11 12:56 UTC, ronag commented
```js
nxt = { 
  ds, // se old expression code
  hashaint, // se old expression code
  asset, // se old expression code
  timer(dueTime, undueValue, dueValue) // re-evaluate after due time and return corresponding value
}
```

2022-10-11 16:29 UTC, kmamal commented
Pushed fixes.
* Using node vm for execution. The global scope is empty in vm which is nice.
* I'm now puttin the context variables (now called `args` to differentiate them from the vm context) in the global scope.
* pipeline operator is in, using hack pipes and the # placeholder
* ds is inside `nxt` and so are `asset` and `hashaint`.

@ronag I'm not exactly sure I understand the timer function. I've put a TODO.

2022-10-11 17:24 UTC, ronag commented on util/template/javascript.js
> +        topicToken: '#',
I think % is more likely for final proposal?

2022-10-11 17:42 UTC, ronag requested changes

2022-10-11 17:42 UTC, ronag commented on util/template/javascript.js
> +            return types.includes(type)
fp.includes is more defensive

2022-10-11 17:42 UTC, ronag commented on util/template/javascript.js
> +          const hasAssetType = (id, type, _return = true) => {
_return does nothing now, maybe throw kEmpty?

2022-10-11 17:43 UTC, ronag commented on util/template/javascript.js
> +            return types.includes(type)
Or at least ?.includes

2022-10-11 17:44 UTC, ronag commented on util/template/javascript.js
> +          const getRecord = (recordId, path, state = ds.record.SERVER) => {
Remove default arg for state

2022-10-11 17:47 UTC, ronag commented on util/template/javascript.js
> +            return types.includes(type)
Return id if true

2022-10-11 18:51 UTC, ronag commented
```
commit fd98541e08a590ce9ca1df3983f3d430213313f0
Author: Robert Nagy <ronagy@icloud.com>
Date:   Tue Oct 11 20:50:59 2022 +0200

    fixup

diff --git a/util/template/javascript.js b/util/template/javascript.js
index c5d796c..09ff5d6 100644
--- a/util/template/javascript.js
+++ b/util/template/javascript.js
@@ -23,7 +23,14 @@ const globals = {
   moment: require('moment'),
 }
 
-const kEmpty = Symbol('kEmpty')
+const kWait = Symbol('kWait')
+const kNull = Symbol('kNull')
+
+const hashaint = (value, _options = {}) => {
+  const str = JSON.stringify(value)
+  const hash = hasha(str, _options)
+  return parseInt(hash.slice(-13), 16)
+}
 
 module.exports = ({ ds } = {}) => {
   return weakCache((expression) => {
@@ -59,27 +66,27 @@ module.exports = ({ ds } = {}) => {
 
             if (state == null) {
               state =
-                recordId.startsWith('{') || recordId.endsWith('?')
+                recordId.startsWith('{') || recordId.includes('?')
                   ? ds.record.PROVIDER
                   : ds.record.SERVER
             }
 
             if (entry.record.state < state) {
-              throw kEmpty
+              throw kWait
             }
 
             return entry.record.get(path)
           }
 
-          const hasAssetType = (id, type, _return = true) => {
+          const hasAssetType = (id, type, throws = true) => {
             const types = getRecord(id + ':asset.rawTypes?', 'value')
-            return types.includes(type)
-          }
-
-          const hashaint = (value, _options = {}) => {
-            const str = JSON.stringify(value)
-            const hash = hasha(str, _options)
-            return parseInt(hash.slice(-13), 16)
+            if (types.includes(type)) {
+              return id
+            }
+            if (throws) {
+              throw kNull
+            }
+            return null
           }
 
           const context = vm.createContext({
@@ -103,7 +110,9 @@ module.exports = ({ ds } = {}) => {
             try {
               o.next(script.runInContext(context))
             } catch (err) {
-              if (err !== kEmpty) {
+              if (err === kNull) {
+                o.next(null)
+              } else if (err !== kWait) {
                 o.error(err)
               }
             }

```

2022-10-11 19:04 UTC, ronag commented
```patch
commit 6e97b6f753dccf9127daf7e00b81dd5b27086dad
Author: Robert Nagy <ronagy@icloud.com>
Date:   Tue Oct 11 20:50:59 2022 +0200

    fixup

diff --git a/util/template/javascript.js b/util/template/javascript.js
index c5d796c..aedf852 100644
--- a/util/template/javascript.js
+++ b/util/template/javascript.js
@@ -23,7 +23,14 @@ const globals = {
   moment: require('moment'),
 }
 
-const kEmpty = Symbol('kEmpty')
+const kWait = Symbol('kWait')
+const kNull = Symbol('kNull')
+
+const hashaint = (value, _options = {}) => {
+  const str = JSON.stringify(value)
+  const hash = hasha(str, _options)
+  return parseInt(hash.slice(-13), 16)
+}
 
 module.exports = ({ ds } = {}) => {
   return weakCache((expression) => {
@@ -44,7 +51,7 @@ module.exports = ({ ds } = {}) => {
             }
           }
 
-          const getRecord = (recordId, path, state = ds.record.SERVER) => {
+          const getRecord = (recordId, path, state) => {
             let entry = records.get(recordId)
             if (!entry) {
               entry = { isUsed: false, record: ds.record.getRecord(recordId) }
@@ -59,27 +66,27 @@ module.exports = ({ ds } = {}) => {
 
             if (state == null) {
               state =
-                recordId.startsWith('{') || recordId.endsWith('?')
+                recordId.startsWith('{') || recordId.includes('?')
                   ? ds.record.PROVIDER
                   : ds.record.SERVER
             }
 
             if (entry.record.state < state) {
-              throw kEmpty
+              throw kWait
             }
 
             return entry.record.get(path)
           }
 
-          const hasAssetType = (id, type, _return = true) => {
-            const types = getRecord(id + ':asset.rawTypes?', 'value')
-            return types.includes(type)
-          }
-
-          const hashaint = (value, _options = {}) => {
-            const str = JSON.stringify(value)
-            const hash = hasha(str, _options)
-            return parseInt(hash.slice(-13), 16)
+          const hasAssetType = (id, type, throws = true) => {
+            const types = getRecord(id + ':asset.rawTypes?', 'value', ds.record.PROVIDER)
+            if (types.includes(type)) {
+              return id
+            }
+            if (throws) {
+              throw kNull
+            }
+            return null
           }
 
           const context = vm.createContext({
@@ -103,7 +110,9 @@ module.exports = ({ ds } = {}) => {
             try {
               o.next(script.runInContext(context))
             } catch (err) {
-              if (err !== kEmpty) {
+              if (err === kNull) {
+                o.next(null)
+              } else if (err !== kWait) {
                 o.error(err)
               }
             }

```

2022-10-12 06:08 UTC, ronag commented
I think all nxt context can live under `nxt.`, i.e. `nxt.id`

2022-10-12 06:08 UTC, ronag commented
https://github.com/babel/babel/issues/15039#issuecomment-1275629199

2022-10-12 07:23 UTC, ronag commented
@deadbeef84 I have already done that: https://github.com/nxtedition/nxt/pull/8574

2022-10-12 07:26 UTC, ronag commented
What I'm missing from e.g. fp.pipe is the ability to short-circuit (which to be fair we don't have in hack pipes yet either).

2022-10-12 07:56 UTC, deadbeef84 commented
> What I'm missing from e.g. fp.pipe is the ability to short-circuit (which to be fair we don't have in hack pipes yet either).

yeah it's mentioned as a future extension for hack pipes, so it's not part of the current proposal so probably wont see it anytime soon. I think our closest bet is something similar to `return()` in nxtpressions? Assuming you want to short-circuit the entire expression :grimacing:

2022-10-13 13:47 UTC, ronag commented on util/template/javascript.js
> +            if (throws) {
I don't think we need this anymore...

2022-10-13 13:49 UTC, ronag approved these changes
LGTM, is this ready?

2022-10-13 14:00 UTC, kmamal commented
* removed hack pipes
* added `nxt.pipe`
* I have made a new PR for changes expressions: https://github.com/nxtedition/nxt/pull/8580

2022-10-13 14:01 UTC, kmamal commented
I'd say it's ready yes.

2022-10-13 14:11 UTC, ronag commented on util/template/javascript.js
> +          pipe.ds = (domain, path, state) => (id) => getRecord(id + domain, path, state)
Maybe we should skip these to begin with?

2022-10-14 10:20 UTC, merged

2022-10-14 10:22 UTC, deadbeef84 commented on util/template/index.js
> +const getNxtpressionsCompiler = require('./nextpressions')
```suggestion
const getNxtpressionsCompiler = require('./nxtpressions')
```

2022-10-14 10:23 UTC, deadbeef84 commented on util/template/javascript.js
> +              ...args,
remove args here?